namespace Censo.API
{
    using System;
    using System.IO;
    using System.Reflection;
    using Domain.Interfaces;
    using Domain.Interfaces.Data;
    using Infra.Data;
    using Infra.Data.Repositories;
    using Infra.Environment;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.OpenApi.Models;

    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // infra services
            services.AddTransient<IMyEnvironment, MyEnvironment>();
            services.AddDbContext<DatabaseContext>();

            // repositories
            services.AddTransient<IRegionRepository, RegionRepository>();
            services.AddTransient<IGenderRepository, GenderRepository>();
            services.AddTransient<ISchoolingRepository, SchoolingRepository>();
            services.AddTransient<IEthnicityRepository, EthnicityRepository>();
            services.AddTransient<IAnswerRepository, AnswerRepository>();

            // controllers
            services.AddControllers();

            // signal r server for real time dashboard
            services.AddSignalRCore();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Census API" });

                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);
            
                //... and tell Swagger to use those XML comments.
                c.IncludeXmlComments(xmlPath);
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseCors();

            app.UseSwagger();
            
            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
