namespace Censo.API
{
    using System;
    using System.IO;
    using System.Reflection;
    using Domain.Interfaces.Data;
    using Infra.Data;
    using Infra.Data.Repositories;
    using Microsoft.AspNetCore.Builder;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.EntityFrameworkCore;
    using Microsoft.EntityFrameworkCore.Diagnostics;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;
    using Microsoft.OpenApi.Models;

    public class Startup
    {
        public IConfiguration Configuration { get; }

        public IHostEnvironment CurrentEnvironment { get; }

        public Startup(IConfiguration configuration, IHostEnvironment environment)
        {
            Configuration = configuration;
            CurrentEnvironment = environment;
        }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            // infra services
            if (CurrentEnvironment.IsEnvironment("IntegrationTest"))
            {
                services.AddDbContext<DatabaseContext>(options => options.UseInMemoryDatabase("database").ConfigureWarnings(w => w.Ignore(InMemoryEventId.TransactionIgnoredWarning)));
            }
            else
            {
                services.AddDbContext<DatabaseContext>(options =>
                {
                    var datasource = Environment.GetEnvironmentVariable("SQL_SERVER_HOST");
                    var database = Environment.GetEnvironmentVariable("SQL_SERVER_DATABASE");
                    var user = Environment.GetEnvironmentVariable("SQL_SERVER_USER");
                    var password = Environment.GetEnvironmentVariable("SQL_SERVER_PASSWORD");

                    options.UseSqlServer($"Data Source={datasource};Initial Catalog={database};Persist Security Info=True;User ID={user};Password={password}");
                });
            }

            // repositories
            services.AddTransient<IRegionRepository, RegionRepository>();
            services.AddTransient<IGenderRepository, GenderRepository>();
            services.AddTransient<ISchoolingRepository, SchoolingRepository>();
            services.AddTransient<IEthnicityRepository, EthnicityRepository>();
            services.AddTransient<IAnswerRepository, AnswerRepository>();

            // controllers
            services.AddControllers();

            // signal r server for real time dashboard
            services.AddSignalRCore();

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new OpenApiInfo { Title = "Census API" });

                //Locate the XML file being generated by ASP.NET...
                var xmlFile = $"{Assembly.GetExecutingAssembly().GetName().Name}.XML";
                var xmlPath = Path.Combine(AppContext.BaseDirectory, xmlFile);

                //... and tell Swagger to use those XML comments.
                c.IncludeXmlComments(xmlPath);
            });
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseHttpsRedirection();

            app.UseRouting();

            app.UseCors();

            app.UseSwagger();

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
            });

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapControllers();
            });
        }
    }
}
