// <auto-generated />
using Censo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Censo.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20200313183253_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Censo.Domain.Model.EthnicityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Ethnicity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Branco"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Pardo"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Preto"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Amarelo"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Indígena"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.GenderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Feminino"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.RegionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Sudeste"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Sul"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Centro-Oeste"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Nordeste"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Norte"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.SchoolingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Schooling");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Fundamental I Incompleto"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Fundamental I Completo"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Fundamental II Incompleto"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Fundamental II Completo"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Médio Imcompleto"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Médio Completo"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Superior Incompleto"
                        },
                        new
                        {
                            Id = 8,
                            Value = "Superior Completo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
