// <auto-generated />
using System;
using Censo.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Censo.Infra.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Censo.Domain.Model.AnswerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EthnicityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int?>("SchoolingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EthnicityId");

                    b.HasIndex("GenderId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SchoolingId");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique()
                        .HasFilter("[FirstName] IS NOT NULL AND [LastName] IS NOT NULL");

                    b.HasIndex("FirstName", "LastName", "GenderId", "RegionId", "EthnicityId", "SchoolingId");

                    b.ToTable("Census_Answers");
                });

            modelBuilder.Entity("Censo.Domain.Model.AnswerParentChildModel", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.HasKey("ParentId", "ChildId");

                    b.HasIndex("ChildId");

                    b.ToTable("Census_AnswersParentChild");
                });

            modelBuilder.Entity("Censo.Domain.Model.EthnicityModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Ethnicity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Branco"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Pardo"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Preto"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Amarelo"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Indígena"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.GenderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Gender");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Masculino"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Feminino"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.RegionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Region");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Sudeste"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Sul"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Centro-Oeste"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Nordeste"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Norte"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.SchoolingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Census_Schooling");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "Fundamental I Incompleto"
                        },
                        new
                        {
                            Id = 2,
                            Value = "Fundamental I Completo"
                        },
                        new
                        {
                            Id = 3,
                            Value = "Fundamental II Incompleto"
                        },
                        new
                        {
                            Id = 4,
                            Value = "Fundamental II Completo"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Médio Imcompleto"
                        },
                        new
                        {
                            Id = 6,
                            Value = "Médio Completo"
                        },
                        new
                        {
                            Id = 7,
                            Value = "Superior Incompleto"
                        },
                        new
                        {
                            Id = 8,
                            Value = "Superior Completo"
                        });
                });

            modelBuilder.Entity("Censo.Domain.Model.AnswerModel", b =>
                {
                    b.HasOne("Censo.Domain.Model.EthnicityModel", "Ethnicity")
                        .WithMany()
                        .HasForeignKey("EthnicityId");

                    b.HasOne("Censo.Domain.Model.GenderModel", "Gender")
                        .WithMany()
                        .HasForeignKey("GenderId");

                    b.HasOne("Censo.Domain.Model.RegionModel", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.HasOne("Censo.Domain.Model.SchoolingModel", "Schooling")
                        .WithMany()
                        .HasForeignKey("SchoolingId");
                });

            modelBuilder.Entity("Censo.Domain.Model.AnswerParentChildModel", b =>
                {
                    b.HasOne("Censo.Domain.Model.AnswerModel", "Child")
                        .WithMany("Parents")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Censo.Domain.Model.AnswerModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
