 version: 2.1

 jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    
     steps:
       - checkout
       - run: 
         name: Restore pakcages   
         command: dotnet restore
       - run:
         name: Build app
         command: dotnet build
         
         
