 version: 2.1

 jobs:
   build:
     docker:
       - image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster
    
     steps:
       - checkout
       - run: 
          name: Restore packages
          command: dotnet restore Censo.API/Censo.API.sln
       - run:
          name: Unit tests
          command: dotnet test Censo.API/Censo.API.sln -v n --results-directory:test_coverage --collect:"Code Coverage"
       - run:
          name: Build app
          command: dotnet build Censo.API/Censo.API.sln -c Release -o /app/build
          